import { describe, expect, it } from "vitest";
import { hashPassword, verifyPassword } from "./auth";

describe("admin password hashing", () => {
  it("accepts the right password and rejects the wrong one", async () => {
    const hash = await hashPassword("a-long-enough-password");
    expect(await verifyPassword("a-long-enough-password", hash)).toBe(true);
    expect(await verifyPassword("a-long-enough-passwore", hash)).toBe(false);
    expect(await verifyPassword("", hash)).toBe(false);
  });

  it("uses a fresh salt on every call", async () => {
    // Identical hashes for identical passwords would give away who reuses one.
    const first = await hashPassword("the-same-password");
    const second = await hashPassword("the-same-password");
    expect(first).not.toBe(second);
    expect(await verifyPassword("the-same-password", second)).toBe(true);
  });

  it("rejects an unknown hash format instead of throwing", async () => {
    expect(await verifyPassword("x", "md5$abc")).toBe(false);
    expect(await verifyPassword("x", "garbage")).toBe(false);
    expect(await verifyPassword("x", "")).toBe(false);
  });

  /**
   * The hash is produced by a Node script (`scripts/create-admin.mjs`) and
   * verified by the Worker through WebCrypto. If the parameters ever drift
   * apart, the owner would create a password and simply not be able to sign in.
   *
   * The fixture below was generated by that script with the password
   * "fixture-password-123". Changing the iteration count or the digest in
   * `auth.ts` without updating the script breaks this test.
   */
  it("accepts a hash produced by scripts/create-admin.mjs", async () => {
    const fromScript =
      "pbkdf2$100000$vi9HU0e7bQnlKMXddVYuaw==$qfQ/as688+EiNjT5DOeeyJ7YTpEutZuNwACRXXHa2jM=";

    expect(await verifyPassword("fixture-password-123", fromScript)).toBe(true);
    expect(await verifyPassword("another-password", fromScript)).toBe(false);
  });
});
